[build]
  command = "npm run build && mkdir -p .cache && echo '{}' > .cache/imageCdnEncryptionConfig.json"
  publish = "dist"
  functions = "netlify/functions"

[build.environment]
  NODE_VERSION = "18"
