// One-shot image optimization for public/images.
// Converts heavy raster images to resized WebP, emits a dimensions manifest
// (for CLS-safe width/height), and rewrites code references .png/.jpg -> .webp.
//
// Run from repo root:  node scripts/optimize-images.mjs
//
// Notes:
// - og-image.png is intentionally skipped (kept PNG for social-card compat).
// - SVGs and favicons are left untouched.
import { readdir, readFile, writeFile, stat } from 'node:fs/promises';
import { join, extname, basename } from 'node:path';
import sharp from 'sharp';

const IMAGES_DIR = 'public/images';
const SRC_DIR = 'src';
const MAX_WIDTH = 1280;
const QUALITY = 78;
const SKIP = new Set(['og-image.png']); // keep as PNG for social cards
const RASTER = new Set(['.png', '.jpg', '.jpeg']);

const manifest = {};
let before = 0;
let after = 0;

const files = await readdir(IMAGES_DIR);
for (const file of files) {
  const ext = extname(file).toLowerCase();
  if (!RASTER.has(ext) || SKIP.has(file)) continue;

  const inPath = join(IMAGES_DIR, file);
  const outName = basename(file, ext) + '.webp';
  const outPath = join(IMAGES_DIR, outName);

  const srcBytes = (await stat(inPath)).size;
  const img = sharp(inPath);
  const meta = await img.metadata();
  const targetWidth = Math.min(meta.width || MAX_WIDTH, MAX_WIDTH);

  const buf = await img
    .resize({ width: targetWidth, withoutEnlargement: true })
    .webp({ quality: QUALITY, effort: 5 })
    .toBuffer({ resolveWithObject: true });

  await writeFile(outPath, buf.data);
  manifest['/images/' + outName] = { width: buf.info.width, height: buf.info.height };
  before += srcBytes;
  after += buf.data.length;
  console.log(
    `${file} ${(srcBytes / 1024).toFixed(0)}KB -> ${outName} ${(buf.data.length / 1024).toFixed(0)}KB`
  );
}

// Write the dimensions manifest (sorted for stable diffs).
const entries = Object.keys(manifest)
  .sort()
  .map((k) => `  '${k}': { width: ${manifest[k].width}, height: ${manifest[k].height} },`)
  .join('\n');
const manifestTs = `// AUTO-GENERATED by scripts/optimize-images.mjs — do not edit by hand.\n// Intrinsic dimensions of optimized images, used to reserve space (CLS).\nexport const imageMeta: Record<string, { width: number; height: number }> = {\n${entries}\n};\n`;
await writeFile(join(SRC_DIR, 'data', 'imageMeta.ts'), manifestTs);

// Rewrite code references: /images/<name>.(png|jpg|jpeg) -> .webp (skip og-image.png).
async function walk(dir) {
  const out = [];
  for (const e of await readdir(dir, { withFileTypes: true })) {
    const p = join(dir, e.name);
    if (e.isDirectory()) out.push(...(await walk(p)));
    else if (/\.(astro|tsx|ts)$/.test(e.name)) out.push(p);
  }
  return out;
}

const codeFiles = await walk(SRC_DIR);
let rewritten = 0;
const refRe = /(\/images\/[a-zA-Z0-9._-]+?)\.(png|jpe?g)\b/g;
for (const f of codeFiles) {
  const text = await readFile(f, 'utf8');
  const next = text.replace(refRe, (m, base, ext) =>
    base === '/images/og-image' ? m : `${base}.webp`
  );
  if (next !== text) {
    await writeFile(f, next);
    rewritten++;
  }
}

console.log(
  `\nImages: ${(before / 1024 / 1024).toFixed(2)}MB -> ${(after / 1024 / 1024).toFixed(2)}MB ` +
    `(${(100 * (1 - after / before)).toFixed(1)}% smaller). Code files rewritten: ${rewritten}.`
);
