name: Check PR

on: [pull_request]

jobs:
  run-ci:
    name: Type check, lint, test
    runs-on: ubuntu-latest
    env:
      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Set up Node
        uses: actions/setup-node@v4
        with:
          node-version-file: '.nvmrc'
          cache: 'npm'

      - name: Install dependencies
        run: npm ci

      - name: Check types
        run: npm run type-check

      - name: Check linting
        run: npm run lint

      - name: Run tests
        run: npm test

      - name: Check commits messages
        uses: wagoid/commitlint-github-action@v6
